// generated by ChatGPT wtf

use hyper::{Client, Request, Body};
use serde_json::Value;

fn api() {
    let client = Client::new();

    // Set up the request
    let request_url = "https://api.fitbit.com/1/user/-/activity/date/2022-01-01.json";
    let request = Request::get(request_url)
        .header("Authorization", "Bearer YOUR_ACCESS_TOKEN")
        .body(Body::empty())
        .unwrap();

    // Send the request and process the response
    let response = client.request(request).and_then(|res| {
        res.into_body().concat2().and_then(|body| {
            let data: Value = serde_json::from_slice(&body).unwrap();
            Ok(data)
        })
    });

    match response {
        Ok(data) => {
            // Do something with the data
            println!("{:?}", data);
        },
        Err(e) => {
            // Handle the error
            println!("Error: {}", e);
        }
    }
}